### ISSUE TITLE
Copy pasting code gives ZWSP in IntelliJ IDEA

### ISSUE THREAD

**Issue by biergit** [openrewrite/rewrite-docs#66] opened 2021-09-13 15:04 UTC
![image](https://user-images.githubusercontent.com/1071968/133108323-4e7b8c9a-0561-4d98-8ff2-4009f92ab596.png)

**Comment by sambsnyd** [comment] 2021-10-13 23:55
I don't see this happen on Windows, copying from Chrome into IntelliJ, Visual Studio Code, or Notepad++.

**Comment by sambsnyd** [comment] 2021-10-14 01:13
I've validated that there are no hidden whitespace characters in that document (aside from the expected LineFeed).
![image](https://user-images.githubusercontent.com/8549033/137233843-8861d1d3-20ad-487d-a35f-4016df4048f2.png)

And since this issue was opened Gitbook's interface has changed, so how they display code has as well. 
Since there are no unexpected characters in the source and I can't reproduce through the current gitbook interface I'm going to close this issue. Thank you for reporting and please let us know if you see similar problems in the future.

**Closed by sambsnyd** 2021-10-14 01:13 UTC
Labels: question
